### ISSUE TITLE
What did i miss ??

### ISSUE THREAD

**Issue by nimdanor** [mciissee/LaRuche2#1]
(venv) MacBook-Pro-de-Dominique:LaRuche2 dominiquerevuz$ ng build
An unhandled exception occurred: Could not find module "@angular-devkit/build-angular" from "/Users/dominiquerevuz/DJANGO/LaRuche2".
See "/private/var/folders/37/c3670s_s7wb22g5n6sv2906c0000gn/T/ng-6iBEfe/angular-errors.log" for further details.

**Comment by mciissee** [comment]
- git clone https://github.com/mciissee/LaRuche2
- cd LaRuche2
- npm install # to generate node_modules from packages.json
- ng serve # to start live dev server
- open http://localhost:4200/ to see the application


ng build --prod command is only used to build the application for distribution purpose

**Comment by mciissee** [comment]
You may run npm commands with sudo on macOS (sudo npm install...)
